version: '3.7'

services:
  dash:
    container_name: dash
    image: crypdex/dash-core:${DASH_VERSION:-0.14}
    restart: on-failure
    volumes:
      - ${DASH_DATA_DIR:?DASH_DATA_DIR required}:/home/dash/.dash
    command: -rpcallowip=0.0.0.0/0
      -printtoconsole
    ports:
      - 9998:9998 # RPC
      - 9999:9999 # P2P
      - 19998:19998 # testnet
      - 19999:19999 # testnet
