#!/usr/bin/env bash

CHAIN="${CHAIN:-bitcoin}"

if [[ ${CHAIN} = "bitcoin" ]]; then
  CONTAINER="${CONTAINER:-lnd-btc}"
  docker exec -it -u lnd ${CONTAINER} lncli -c bitcoin $@
else
  CONTAINER="${CONTAINER:-lnd-ltc}"
  docker exec -it -u lnd ${CONTAINER} lncli -c litecoin $@
fi

