version: "3.7"

services:

  lnd_litecoin:
    image: crypdex/lnd:0.6
    container_name: lnd_litecoin
    restart: on-failure
    depends_on:
      - litecoin
    environment:
      - CHAIN=litecoin
      - BACKEND=${LND_LITECOIN_BACKEND:-litecoind}
      - NETWORK=${LITECOIN_NETWORK:-mainnet}
      - LITECOIN_RPCUSER=${LITECOIN_RPCUSER:?LITECOIN_RPCUSER is required}
      - LITECOIN_RPCPASS=${LITECOIN_RPCPASS:?LITECOIN_RPCPASS is required}
    command:
      --rpclisten=0.0.0.0:10009
    volumes:
      - ${DATA_DIR}/${LND_DIR:-lnd}:/home/lnd/.lnd

  litecoin:
    image: crypdex/litecoin:${LITECOIN_VERSION:-0.17}
    container_name: litecoind
    restart: on-failure
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/${LITECOIN_DIR:-litecoin}:/home/litecoin/.litecoin
    environment:
      - NETWORK=${LITECOIN_NETWORK-mainnet}
    ports:
      - 9332:9332 # RPC
      - 9333:9333 # P2P
      - 19332:19332
      - 19333:19333
      - 19444:19444
    command:
      -rpcuser=${LITECOIN_RPCUSER:?LITECOIN_RPCUSER is required}
      -rpcpassword=${LITECOIN_RPCPASS:?LITECOIN_RPCPASS is required}
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28334
      -printtoconsole
      -txindex

