version: "3.7"

services:
  api:
    image: crypdex/blackbox-api:latest
    container_name: api
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres?sslmode=disable
    ports:
      - "80:4000"
    restart: "unless-stopped"
    depends_on:
      - postgres
    command:
      ["/root/wait-for-it/wait-for-it.sh", "postgres:5432", "--", "./app"]
  # API DEPENDENCIES
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/postgres:/var/lib/postgresql/data
    restart: "unless-stopped"
