version: '3'

services:
  # postgres is a multiarch image
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/postgres:/var/lib/postgresql/data
  mail:
    image: crypdex/postfix-relay:latest
    ports:
      - '1587:25'
    environment:
      - SMTP_HOST=smtp.sendgrid.com
      - SMTP_PORT=587
      - SMTP_LOGIN=apikey
      - SMTP_PASSWORD=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

  # api:
  #   image: crypdex/blackbox-api-arm64:latest
  #   container_name: api
  #   volumes:
  #     - ${DATA_DIR:?DATA_DIR required}/blackbox-api:/root/resources
  #   environment:
  #     - PORT=4000
  #     - DATABASE_URL=postgres://postgres@postgres:5432/postgres?sslmode=disable
  #   ports:
  #     - '80:4000'
  #   restart: on-failure
  #   depends_on:
  #     - postgres
  #   command: ['/root/wait-for-it/wait-for-it.sh', 'postgres:5432', '--', './app']
