version: "3.7"

# WARNING: DO NOT CHANGE THE CONTAINER NAME
# It is used by walletnotify.sh to target this service
services:
  api:
    image: crypdex/blackbox-api:edge
    container_name: api
    restart: "unless-stopped"
    env_file:
      - ./.blackbox.env
    environment:
      - DATA_DIR=${DATA_DIR}
    volumes:
      - ${DATA_DIR:?DATA_DIR required}:/root/data
      - .:/root/blackbox
    ports:
      - "80:4000"
    depends_on:
      - postgres
    command:
      ["/root/wait-for-it/wait-for-it.sh", "postgres:5432", "--", "./app"]
