version: "3.7"

services:
  # ----------
  # POSTGRES
  # ----------
  postgres:
    image: postgres
    container_name: postgres
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/postgres:/var/lib/postgresql/data
  # ----------
  # SMTP RELAY
  # ----------
#  smtp-relay:
#    image: crypdex/smtp-relay:latest
#    container_name: smtp-relay
#    restart: "unless-stopped"
#    ports:
#      - "127.0.0.1:1587:25"
#    # The SMTP_PASSWORD should not be in here, but how can I rotate it?
#    environment:
#      - SMTP_HOST=smtp.sendgrid.com
#      - SMTP_PORT=587
#      - SMTP_LOGIN=apikey
  # ----------
  # OUROBOROS
  # ----------
#  ouroboros:
#    container_name: ouroboros
#    hostname: ouroboros
#    image: pyouroboros/ouroboros
#    restart: unless-stopped
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - postgres
#      - smtp-relay
#    environment:
#      - CLEANUP=true
#      - INTERVAL=60
#      - LOG_LEVEL=info
#      - SELF_UPDATE=false
#      - IGNORE=postgres
#      - TZ=America/New_York