version: "3.7"

services:
  api:
    image: crypdex/blackbox-api:latest
    container_name: api
    env_file:
      - ./.blackbox.env
      - ./.encryption-key.env
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres?sslmode=disable
      - DATA_DIR=${DATA_DIR}
    volumes:
      - ${DATA_DIR:?DATA_DIR required}:/root/data
    ports:
      - "80:4000"
    restart: "unless-stopped"
    depends_on:
      - postgres
    command:
      ["/root/wait-for-it/wait-for-it.sh", "postgres:5432", "--", "./app"]
