version: "3.7"

# NOTE: THIS IS NOT A MULTIARCH IMAGE

services:
  litecoin:
    image: uphold/litecoin-core:latest
    restart: "unless-stopped"
    ports:
      - "9332:9332" # RPC
      - "9333:9333" # P2P
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/litecoin:/home/litecoin/.litecoin
    # Command-line options override values set in the configuration file.
    command: -rpcallowip=0.0.0.0/0 -txindex=1 -printtoconsole



