# The GPG key created for this requires no password to sign

version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Import GPG key
          command: echo -e "$GPG_KEY" | gpg --import
      - run:
          command: |
            curl -sL https://git.io/goreleaser |  \
            bash -s -- --snapshot --skip-publish --rm-dist --release-notes=docs/release-notes/latest.md
            ls dist/ | grep -i '.*[.]deb'

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              only: master
              ignore: gh-pages
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/