version: "3.7"

services:
  dcrd:
    image: crypdex/decred
    ports:
      - "9108:9108"
      - "9109:9109"
    volumes:
      - ${DECRED_DATA_DIR:?DECRED_DATA_DIR required}/Dcrd:/home/decred/.decred
    # Command-line options override values set in the configuration file.
    command: dcrd --notls --rpcuser=dmichael --rpcpass=123
#      --externalip=$DECRED_EXTERNALIP
  dcrwallet:
    image: crypdex/decred
    ports:
      - "9110:9110"
      - "9111:9111"
    volumes:
      - ${DECRED_DATA_DIR:?DECRED_DATA_DIR required}/Dcrwallet:/home/decred/.dcrwallet
    # Command-line options override values set in the configuration file.
    command: dcrwallet --enablevoting --noinitialload




