version: "3.7"

# While the RPC allow is set open, the ports only bind to localhost.

services:
  zcoin:
    image: crypdex/zcoin
    container_name: zcoin
    restart: "unless-stopped"
    ports:
      - "8888:8888" # RPC
      - "8168:8168" # P2P
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/zcoin:/home/zcoin/.zcoin
    # Command-line options override values set in the configuration file.
    command: -rpcallowip=0.0.0.0/0 -txindex=1



