version: "3.7"

services:
  blocknet:
    image: crypdex/blocknet:${BLOCKNETDX_VERSION:-3.13}
    volumes:
      - ${BLOCKNETDX_DATA_DIR:?BLOCKNETDX_DATA_DIR required}:/home/blocknet/.blocknet
    command: --printtoconsole
    ports:
      - 41412:41412 # RPC
      - 41414:41414 # P2P
