version: "3.7"

services:
  postgres:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA_DIR:?POSTGRES_DATA_DIR required}:/var/lib/postgresql/data