version: "3.7"

services:

  lnd_bitcoin:
    image: crypdex/lnd:0.6
    container_name: lnd_bitcoin
    restart: on-failure
    command:
      --rpclisten=0.0.0.0:10009
    volumes:
      - ${LND_BITCOIN_DATA_DIR:?LND_BITCOIN_DATA_DIR required}:/home/lnd/.lnd


