version: "3.7"

services:

  lnd_bitcoin:
    image: crypdex/lnd:0.6
    container_name: lnd_bitcoin
    restart: on-failure
    depends_on:
      - bitcoin
    environment:
      - CHAIN=bitcoin
      - BACKEND=${LND_BITCOIN_BACKEND:-bitcoind}
      - NETWORK=${BITCOIN_NETWORK:-mainnet}
      - BITCOIN_RPCUSER=${BITCOIN_RPCUSER:?BITCOIN_RPCUSER is required}
      - BITCOIN_RPCPASS=${BITCOIN_RPCPASS:?BITCOIN_RPCPASS is required}
    command:
      --rpclisten=0.0.0.0:10009
    volumes:
      - ${DATA_DIR}/${LND_DIR:-lnd}:/home/lnd/.lnd

  bitcoin:
    image: crypdex/bitcoin:${BITCOIN_VERSION:-0.17}
    container_name: bitcoind
    restart: on-failure
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/${BITCOIN_DIR:-bitcoin}:/home/bitcoin/.bitcoin
    environment:
      - BITCOIN_NETWORK=${BITCOIN_NETWORK-mainnet}
    ports:
      - 8332:8332
      - 8333:8333
      - 18332:18332
      - 18333:18333
      - 18443:18443
      - 18444:18444
    command:
      -rpcuser=${BITCOIN_RPCUSER:?BITCOIN_RPCUSER is required}
      -rpcpassword=${BITCOIN_RPCPASS:?BITCOIN_RPCPASS is required}
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28334
      -printtoconsole
      -txindex

