version: '3.7'

services:
  pivx:
    image: crypdex/pivx:${PIVX_VERSION:-3.2}
    ports:
      - '51472:51472'
      - '51473:51473'
    volumes:
      - ${PIVX_DATA_DIR:?PIVX_DATA_DIR required}:/home/pivx/.pivx
    # command: -rpcallowip=172.0.0.0/8
    # Command-line options override values set in the configuration file.
    command: ${PIVX_COMMAND:--printtoconsole} --datadir=/home/pivx/.pivx
