version: '3.7'

# While the RPC allow is set open, the ports only bind to localhost.

services:
  pivx:
    image: crypdex/pivx:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/pivx:/home/pivx/.pivx
      # - ${CONFIG_DIR:?CONFIG_DIR required}:/home/pivx/config
    # command: -conf=/home/pivx/config/pivx.conf -rpcallowip=172.0.0.0/8
    # command: -rpcallowip=172.0.0.0/8
    command: -rpcallowip=0.0.0.0/0
    # HOST:CONTAINER
    ports:
      - mode: host
        target: 51472
        published: 51472
     - mode: host
        target: 51473
        published: 51473

