version: '3.7'

# While the RPC allow is set open, the ports only bind to localhost.

services:
  pivx:
    image: crypdex/pivx:3.1
    # Ports are exposed so that users can validate correctness of the chain.
    ports:
      - '51472:51472'
      - '51473:51473'
    volumes:
      - ${PIVX_DATA_DIR:?PIVX_DATA_DIR required}:/home/pivx/.pivx
    # command: -rpcallowip=172.0.0.0/8
    # Command-line options override values set in the configuration file.
    command: -rpcallowip=0.0.0.0/0
      -enablezeromint=0
      -checkblocks=25
      -maxconnections=10
      -printtoconsole
