version: "3.7"

# While the RPC allow is set open, the ports only bind to localhost.

services:
  pivx:
    image: crypdex/pivx:latest
    container_name: pivx
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/pivx:/home/pivx/.pivx
    # command: -rpcallowip=172.0.0.0/8
    # Command-line options override values set in the configuration file.
    command: -rpcallowip=0.0.0.0/0
      -walletnotify=/home/pivx/.pivx/walletnotify.sh
      -enablezeromint=0
      -rpcuser=crypdex
      -rpcpassword=blackbox
      -maxconnections=4
      -checkblocks=30
    ports:
      - "127.0.0.1:51472:51472"
      - "127.0.0.1:51473:51473"
    restart: "unless-stopped"
