##########################################
#
# Sparkswap Broker-CLI and Broker-Daemon
# https://sparkswap.com
#
# Troubleshooting GRPC:
# - GRPC_VERBOSITY=INFO
# - GRPC_TRACE=all
#
##########################################

version: "3.7"

services:
  sparkswap:
    image: crypdex/sparkswap-broker:0.6.2-beta
    depends_on:
      - lnd_btc
      - lnd_ltc
    ports:
      - "27492:27492"
      - "27592:27592"
    working_dir: "/home/app"
    volumes:
      # block order and other sparkswap storage
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/data:/data"
      # This is populated externally w/ an engine
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/shared:/shared"
      # Persistent certs/keys for broker
      - "${SPARKSWAP_SECURE_PATH:?SPARKSWAP_SECURE_PATH is required}:/secure"
    environment:
      - NODE_ENV=production
      # - DATA_DIR=${DATA_DIR:-}
      - NETWORK=${SPARKSWAP_NETWORK:-mainnet}
      - RPC_ADDRESS=${RPC_ADDRESS:-}
      - RPC_HTTP_PROXY_ADDRESS=${RPC_HTTP_PROXY_ADDRESS:-}
      - RPC_USER=${SPARKSWAP_RPC_USER:?SPARKSWAP_RPC_USER is required}
      - RPC_PASS=${SPARKSWAP_RPC_PASSWORD:?SPARKSWAP_RPC_PASSWORD is required}
      - RPC_PUB_KEY=${RPC_PUB_KEY:-}
      - RPC_PRIV_KEY=${RPC_PRIV_KEY:-}
      - ID_PRIV_KEY=${ID_PRIV_KEY:-}
      - ID_PUB_KEY=${ID_PUB_KEY:-}
      - RELAYER_RPC_HOST=${SPARKSWAP_RELAYER_RPC_HOST:-relayer.mainnet.sparkswap.com:28492}
      - RELAYER_CERT_PATH=${SPARKSWAP_RELAYER_CERT_PATH:-}


  # -------------
  # LIGHTNING LTC
  # -------------
  lnd_btc:
    image: crypdex/sparkswap-lnd-btc:0.5.2-beta
    depends_on:
      - bitcoin
    ports:
      - "10113:9735"
    volumes:
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/shared:/shared"
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/lnd_btc:/data"
    logging:
      options:
        max-size: 50m
    environment:
      - RPC_HOST=${BTC_RPC_HOST:-bitcoin}
      - RPC_USER=${SPARKSWAP_BTC_RPC_USER:?SPARKSWAP_BTC_RPC_USER is required}
      - RPC_PASS=${SPARKSWAP_BTC_RPC_PASSWORD:?SPARKSWAP_BTC_RPC_PASSWORD is required}
      - NETWORK=${SPARKSWAP_NETWORK:-mainnet}
      - DEBUG=info
      - EXTERNAL_ADDRESS="${SPARKSWAP_EXTERNAL_BTC_ADDRESS:?SPARKSWAP_EXTERNAL_BTC_ADDRESS is required}:10113"
      - EXTPREIMAGE_HOST=sparkswap:40369
      - ZMQPUBRAWBLOCK=tcp://bitcoin:28333
      - ZMQPUBRAWTX=tcp://bitcoin:28334

  # -------------
  # LIGHTNING LTC
  # -------------
  lnd_ltc:
    image: crypdex/sparkswap-lnd-ltc:0.5.0-beta
    depends_on:
      - litecoin
    ports:
      - "10114:9735"
    volumes:
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/shared:/shared"
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/lnd_ltc:/data"
    logging:
      options:
        max-size: 50m
    environment:
      - RPC_HOST=litecoin
      - RPC_USER=${SPARKSWAP_LTC_RPC_USER:?SPARKSWAP_LTC_RPC_USER is required}
      - RPC_PASS=${SPARKSWAP_LTC_RPC_PASSWORD:?SPARKSWAP_LTC_RPC_PASSWORD is required}
      - NETWORK=${SPARKSWAP_NETWORK:-mainnet}
      - ZMQPUBRAWBLOCK=tcp://litecoin:28333
      - ZMQPUBRAWTX=tcp://litecoin:28334
      - DEBUG=info
      - EXTERNAL_ADDRESS="${SPARKSWAP_EXTERNAL_LTC_ADDRESS?SPARKSWAP_EXTERNAL_LTC_ADDRESS is required}:10114"
      - EXTPREIMAGE_HOST=sparkswap:40369
