##########################################
#
# Sparkswap Broker-CLI and Broker-Daemon
# https://sparkswap.com
#
# Troubleshooting GRPC:
# - GRPC_VERBOSITY=INFO
# - GRPC_TRACE=all
#
##########################################

version: "3.7"

services:
  sparkswapd:
    image: sparkswap/broker:0.5.2-beta
    depends_on:
      - lnd_btc
      - lnd_ltc
    volumes:
      # block order and other sparkswap storage
      - "${DATA_DIR:?DATA_DIR is required}/sparkswap/data:/data"
      # This is populated externally w/ an engine
      - "${DATA_DIR:?DATA_DIR is required}/sparkswap/shared:/shared"
      # Persistent certs/keys for broker
      - "${SECURE_PATH}:/secure"
    environment:
      - NODE_ENV=production
      # - DATA_DIR=${DATA_DIR:-}
      - NETWORK=${NETWORK}
      - RPC_ADDRESS=${RPC_ADDRESS:-}
      - RPC_HTTP_PROXY_ADDRESS=${RPC_HTTP_PROXY_ADDRESS:-}
      - RPC_USER=${RPC_USER}
      - RPC_PASS=${RPC_PASS}
      - RPC_PUB_KEY=${RPC_PUB_KEY:-}
      - RPC_PRIV_KEY=${RPC_PRIV_KEY:-}
      - ID_PRIV_KEY=${ID_PRIV_KEY:-}
      - ID_PUB_KEY=${ID_PUB_KEY:-}
      - RELAYER_RPC_HOST=${RELAYER_RPC_HOST}
      - RELAYER_CERT_PATH=${RELAYER_CERT_PATH:-}
    ports:
      - "27492:27492"
      - "27592:27592"
    networks:
      - broker
    working_dir: "/home/app"
  # -------------
  # LIGHTNING LTC
  # -------------
  lnd_btc:
    image: sparkswap/lnd_btc:0.4.1-beta
    ports:
      - "10113:9735"
    environment:
      - RPC_HOST=${BTC_RPC_HOST:-bitcoind}
      - RPC_USER=${BTC_RPC_USER}
      - RPC_PASS=${BTC_RPC_PASS}
      - NETWORK=${NETWORK}
      - DEBUG=info
      - EXTERNAL_ADDRESS="${EXTERNAL_BTC_ADDRESS}:10113"
      - EXTPREIMAGE_HOST=sparkswapd:40369
      - ZMQPUBRAWBLOCK=${BTC_ZMQPUBRAWBLOCK:-}
      - ZMQPUBRAWTX=${BTC_ZMQPUBRAWTX:-}
      - ZMQPUBRAWBLOCK=tcp://bitcoind:28333
      - ZMQPUBRAWTX=tcp://bitcoind:28334
    volumes:
      - "${DATA_DIR:?DATA_DIR is required}/sparkswap/shared:/shared"
      - "${DATA_DIR:?DATA_DIR is required}/lnd_btc:/data"
    networks:
      - broker
    logging:
      options:
        max-size: 50m
    depends_on:
      - bitcoind
  # -------------
  # LIGHTNING LTC
  # -------------
  lnd_ltc:
    depends_on:
      - litecoind
    environment:
      - RPC_HOST=litecoind
      - ZMQPUBRAWBLOCK=tcp://litecoind:28333
      - ZMQPUBRAWTX=tcp://litecoind:28334
      - RPC_USER=${LTC_RPC_USER:?LTC_RPC_USER is required}
      - RPC_PASS=${LTC_RPC_PASS:?LTC_RPC_PASS is required}
      - RPC_HOST=${LTC_RPC_HOST:-}
      - NETWORK=${NETWORK}
      - DEBUG=info
      - EXTERNAL_ADDRESS="${EXTERNAL_LTC_ADDRESS}:10114"
      - EXTPREIMAGE_HOST=sparkswapd:40369
    image: sparkswap/lnd_ltc:0.4.1-beta
    ports:
      - "10114:9735"
    volumes:
      - "${DATA_DIR:?DATA_DIR is required}/sparkswap/shared:/shared"
      - "${DATA_DIR:?DATA_DIR is required}/lnd_ltc:/data"
    networks:
      - broker
    logging:
      options:
        max-size: 50m