##########################################
#
# Sparkswap Broker-CLI and Broker-Daemon
# https://sparkswap.com
#
# Troubleshooting GRPC:
# - GRPC_VERBOSITY=INFO
# - GRPC_TRACE=all
#
##########################################

version: "3.7"

services:
  sparkswap:
    image: crypdex/sparkswap-broker:0.7.0-beta
    container_name: sparkswap
    restart: on-failure
    depends_on:
      - lnd_btc
      - lnd_ltc
    ports:
      - 27492:27492
      - 27592:27592
    working_dir: "/home/app"
    volumes:
      # block order and other sparkswap storage
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/data:/data"
      # This is populated externally w/ an engine
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/shared:/shared"
      # Persistent certs/keys for broker
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/secure:/secure"
    environment:
      - NODE_ENV=production
      # - DATA_DIR=${DATA_DIR:-}
      - NETWORK=${SPARKSWAP_NETWORK:-mainnet}
      - RPC_ADDRESS=${SPARKSWAP_RPC_ADDRESS:-}
      - RPC_USER=${SPARKSWAP_RPC_USER:?SPARKSWAP_RPC_USER is required}
      - RPC_PASS=${SPARKSWAP_RPC_PASS:?SPARKSWAP_RPC_PASS is required}

      - RPC_HTTP_PROXY_ADDRESS=${SPARKSWAP_RPC_HTTP_PROXY_ADDRESS:-}
      - RPC_PUB_KEY=${SPARKSWAP_RPC_PUB_KEY:-}
      - RPC_PRIV_KEY=${SPARKSWAP_RPC_PRIV_KEY:-}
      - ID_PRIV_KEY=${SPARKSWAP_ID_PRIV_KEY:-}
      - ID_PUB_KEY=${SPARKSWAP_ID_PUB_KEY:-}
      - RELAYER_RPC_HOST=${SPARKSWAP_RELAYER_RPC_HOST:-relayer.mainnet.sparkswap.com:28492}
      - RELAYER_CERT_PATH=${SPARKSWAP_RELAYER_CERT_PATH:-}


  # -------------
  # LIGHTNING BTC
  # -------------
  lnd_btc:
    image: crypdex/sparkswap-lnd-btc:0.5.2-beta
    container_name: lnd_btc
    restart: on-failure
    depends_on:
      - bitcoin
    ports:
      - 10113:9735
    volumes:
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/shared:/shared"
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/lnd_btc:/data"
    logging:
      options:
        max-size: 50m
    environment:
      - DEBUG=info
      - EXTPREIMAGE_HOST=sparkswap:40369
      - NETWORK=${SPARKSWAP_NETWORK:-mainnet}

      - RPC_HOST=${BITCOIN_RPCHOST:-bitcoind}
      - RPC_USER=${BITCOIN_RPCUSER:?BITCOIN_RPCUSER is required}
      - RPC_PASS=${BITCOIN_RPCPASS:?BITCOIN_RPCPASS is required}

      - ZMQPUBRAWBLOCK=tcp://${BITCOIN_RPCHOST:-bitcoin}:28333
      - ZMQPUBRAWTX=tcp://${BITCOIN_RPCHOST:-bitcoin}:28334
      # No longer required
      - EXTERNAL_ADDRESS="${SPARKSWAP_EXTERNAL_BTC_ADDRESS:-}"
      # - EXTERNAL_ADDRESS="${SPARKSWAP_EXTERNAL_BTC_ADDRESS:?SPARKSWAP_EXTERNAL_BTC_ADDRESS is required}:10113"

  # -------------
  # LIGHTNING LTC
  # -------------
  lnd_ltc:
    image: crypdex/sparkswap-lnd-ltc:0.5.2-beta
    container_name: lnd_ltc
    restart: on-failure
    depends_on:
      - litecoin
    ports:
      - "10114:9735"
    volumes:
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/shared:/shared"
      - "${SPARKSWAP_DATA_DIR:?SPARKSWAP_DATA_DIR is required}/lnd_ltc:/data"
    logging:
      options:
        max-size: 50m
    environment:
      - DEBUG=info
      - EXTPREIMAGE_HOST=sparkswap:40369
      - NETWORK=${SPARKSWAP_NETWORK:-mainnet}
      - RPC_HOST=${SPARKSWAP_LTC_RPCHOST:-litecoind}
      - RPC_PASS=${LITECOIN_RPCPASS:?LITECOIN_RPCPASS is required}
      - RPC_USER=${LITECOIN_RPCUSER:?LITECOIN_RPCUSER is required}
      - ZMQPUBRAWBLOCK=tcp://${SPARKSWAP_LTC_RPCHOST:-litecoind}:28333
      - ZMQPUBRAWTX=tcp://${SPARKSWAP_LTC_RPCHOST:-litecoind}:28334
      # No longer required
#      - EXTERNAL_ADDRESS="${SPARKSWAP_EXTERNAL_LTC_ADDRESS?SPARKSWAP_EXTERNAL_LTC_ADDRESS is required}:10114"
      - EXTERNAL_ADDRESS="${SPARKSWAP_EXTERNAL_LTC_ADDRESS:-}"