#!/usr/bin/env bash

# A wrapper script so that blackboxd is transparent

if [[ $1 == "upgrade" ]]; then
  blackboxd stop && apt update && apt install --only-upgrade blackboxd && blackboxd start
elif [[ $1 == "start" ]]; then
  blackboxd start
elif [[ $1 == "stop" ]]; then
  blackboxd stop
elif [[ $1 == "logs" ]]; then
  blackboxd logs
else
  docker exec -ti $(docker ps -qf "name=sparkswap") sparkswap $@
fi