#!/usr/bin/env bash

if [[ $1 == "start" ]]; then
  blackboxd start
elif [[ $1 == "stop" ]]; then
  blackboxd stop
elif [[ $1 == "logs" ]]; then
  blackboxd logs
else
  docker exec -ti $(docker ps -qf "name=sparkswap") sparkswap $@
fi