version: "3.7"

services:
  ##############
  # BITCOIN LND
  ##############

  lnd-btc:
    image: crypdex/lnd:0.6
    container_name: lnd-btc
    restart: on-failure
    depends_on:
      - bitcoin
    # bitcoin.active, bitcoin.mainnet are defaults
    # We choose bitcoind (not btcd) for now
    command:
      --bitcoin.active
      --bitcoin.mainnet
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoin
      --bitcoind.rpcuser=abc
      --bitcoind.rpcpass=123
      --bitcoind.zmqpubrawblock=tcp://bitcoin:28333
      --bitcoind.zmqpubrawtx=tcp://bitcoin:28334
      --rpclisten=0.0.0.0:10009
    volumes:
      - /Volumes/T5/data/lnd:/home/lnd/.lnd
#    ports:
#      - 9735:9735
#      - 10009:10009 # expose the RPC so lncli can get in touch


  ##########
  # BITCOIN
  ##########

  bitcoin:
    image: crypdex/bitcoin-core:0.17
    container_name: bitcoin # Without this, lnd cannot reach the bitcoin daemon
    restart: on-failure
    # -zmq* and -rpcallowip flags are necessary
    command:
      -rpcuser=abc
      -rpcpassword=123
      -printtoconsole
      -txindex
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28334
    ports:
      - 8332:8332 # RPC
      - 8333:8333 # P2P
    volumes:
      - /Volumes/T5/data/bitcoin:/home/bitcoin/.bitcoin

  ###############
  # LITECOIN LND
  ###############

  lnd-ltc:
    image: crypdex/lnd:0.6
    restart: on-failure
    container_name: lnd-ltc
    command:
      --litecoin.active
      --litecoin.mainnet
      --litecoin.node=litecoind
      --litecoind.rpchost=litecoin
      --litecoind.rpcuser=abc
      --litecoind.rpcpass=123
      --litecoind.zmqpubrawblock=tcp://litecoin:28333
      --litecoind.zmqpubrawtx=tcp://litecoin:28334
      --rpclisten=0.0.0.0:10009
    depends_on:
      - litecoin
    volumes:
      - /Volumes/T5/data/lnd:/home/lnd/.lnd
#    ports:
#      - 9735:9735
#      - 10009:10009 # expose the RPC so lncli can get in touch


  ###########
  # LITECOIN
  ###########

  litecoin:
    image: crypdex/litecoin-core:0.17
    container_name: litecoin # Without this, lnd cannot reach the litecoin daemon
    restart: on-failure
    # -zmq* and -rpcallowip flags are necessary
    command:
      -rpcuser=abc
      -rpcpassword=123
      -printtoconsole
      -txindex
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28334
    ports:
      - 9332:9332 # RPC
      - 9333:9333 # P2P
    volumes:
      - /Volumes/T5/data/litecoin:/home/litecoin/.litecoin
