version: '3'

services:
  pivx:
    image: crypdex/pivx-aarch64:latest
    build:
      context: .
      dockerfile: Dockerfile
    # HOST:CONTAINER
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/pivx:/home/pivx/.pivx
      - ${CONF_DIR:?CONF_DIR required}:/home/pivx/config
    # The default command points the conf file mounted in volumes
    # and exposes the RPC to the Docker host
    command: -conf=/home/pivx/config/pivx.conf -rpcallowip=172.0.0.0/8
    # HOST:CONTAINER
    ports:
      - '51472:51472' # masternode connections
      # - '127.0.0.1:51473:51473' # internal only - good default
      # - '51473:51473' # open to the network - the exposes you!
      - ${PIVX_PORTS:-127.0.0.1:51473:51473} # open to the network

