version: '3.4'

services:
  pivx:
    container_name: pivx
    image: crypdex/pivx-arm64:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # HOST:CONTAINER
    volumes:
      - ${DATA_DIR:?DATA_DIR required}/pivx:/home/pivx/.pivx
      - ${CONFIG_DIR:?CONFIG_DIR required}:/home/pivx/config
    # The default command points the conf file mounted in volumes
    # and exposes the RPC to the Docker host
    command: -conf=/home/pivx/config/pivx.conf -rpcallowip=172.0.0.0/8
    # HOST:CONTAINER
    ports:
      - '51472:51472' # masternode connections
      - '51473:51473'
